# Generated by Django 5.2.17 on 2026-08-05 16:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hubdocument",
            name="allow_copy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hubdocument",
            name="allow_download",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="hubdocument",
            name="visible_positions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="hubtrainingmaterial",
            name="visible_positions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="HubResourceFolder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("documents", "Documents"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=32,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "unique_together": {("name", "kind")},
            },
        ),
        migrations.AddField(
            model_name="hubdocument",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="hub.hubresourcefolder",
            ),
        ),
        migrations.AddField(
            model_name="hubtrainingmaterial",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="training_materials",
                to="hub.hubresourcefolder",
            ),
        ),
    ]
