# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0003_hubuser_password_configured"),
    ]

    operations = [
        migrations.AddField(
            model_name="hubuser",
            name="otp_code",
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="hubuser",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
