# Generated by Django 5.2.17 on 2026-08-14 13:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0005_leave_jobber_vacation"),
    ]

    operations = [
        migrations.CreateModel(
            name="HubNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("link", models.CharField(blank=True, default="", max_length=512)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event_key",
                    models.CharField(
                        blank=True, max_length=191, null=True, unique=True
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="hub.hubuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "read_at", "-created_at"],
                        name="hub_hubnoti_recipie_6be0c5_idx",
                    )
                ],
            },
        ),
    ]
