# Generated by Django 5.2.17 on 2026-08-18

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0006_hubnotification"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="hubuser",
            index=models.Index(fields=["jobber_id"], name="hub_hubuser_jobber__idx"),
        ),
        migrations.CreateModel(
            name="HubVisit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("jobber_visit_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                (
                    "client_jobber_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("client_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "jobber_job_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("job_type", models.CharField(blank=True, default="", max_length=64)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                (
                    "technicians",
                    models.ManyToManyField(
                        blank=True, related_name="jobber_visits", to="hub.hubuser"
                    ),
                ),
            ],
            options={
                "ordering": ["-start_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="hubvisit",
            index=models.Index(
                fields=["client_jobber_id"], name="hub_hubvisi_client__idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hubvisit",
            index=models.Index(
                fields=["jobber_job_id"], name="hub_hubvisi_jobber__idx"
            ),
        ),
        migrations.CreateModel(
            name="PendingLockIn",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quote_id", models.CharField(max_length=255, unique=True)),
                ("client_jobber_id", models.CharField(db_index=True, max_length=255)),
                ("client_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "recurring_jobber_job_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("original_visit_ids", models.JSONField(blank=True, default=list)),
                ("quote_accepted", models.BooleanField(default=True)),
                ("locked_in", models.BooleanField(default=False)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("quote_sent_at", models.DateTimeField(blank=True, null=True)),
                ("quote_approved_at", models.DateTimeField(blank=True, null=True)),
                ("frequency", models.CharField(blank=True, default="", max_length=64)),
                ("eligibility_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expected_first_visit_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "first_recurring_visit_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "first_recurring_visit_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "technicians",
                    models.ManyToManyField(
                        blank=True, related_name="pending_lock_ins", to="hub.hubuser"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_process", "In Process"),
                            ("confirmed", "Confirmed"),
                            ("expired", "Expired"),
                        ],
                        default="in_process",
                        max_length=32,
                    ),
                ),
                (
                    "expired_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("confirmation_sms_sent", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="pendinglockin",
            index=models.Index(
                fields=["client_jobber_id", "locked_in"],
                name="hub_pending_client__idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pendinglockin",
            index=models.Index(fields=["status"], name="hub_pending_status_idx"),
        ),
        migrations.CreateModel(
            name="LockInBonus",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pending",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonuses",
                        to="hub.pendinglockin",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lock_in_bonuses",
                        to="hub.hubuser",
                    ),
                ),
                ("bonus_type", models.CharField(default="Locked-In", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_process", "In Process"),
                            ("confirmed", "Confirmed"),
                            ("expired", "Expired"),
                            ("paid", "Paid"),
                        ],
                        default="in_process",
                        max_length=32,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "position_snapshot",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("in_process_date", models.DateTimeField(blank=True, null=True)),
                ("confirmed_date", models.DateTimeField(blank=True, null=True)),
                ("bonus_confirmed", models.BooleanField(default=False)),
                ("bonus_paid", models.BooleanField(default=False)),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                (
                    "payroll_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("potential_sms_sent", models.BooleanField(default=False)),
                ("confirmation_sms_sent", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("pending", "technician")},
            },
        ),
        migrations.AddIndex(
            model_name="lockinbonus",
            index=models.Index(fields=["status"], name="hub_lockinb_status_idx"),
        ),
        migrations.AddIndex(
            model_name="lockinbonus",
            index=models.Index(
                fields=["technician", "status"], name="hub_lockinb_tech_st_idx"
            ),
        ),
    ]
