# Generated by Django 5.2.17 on 2026-08-20 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_lock_in_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HubApiKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('prefix', models.CharField(db_index=True, max_length=16)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='hubuser',
            new_name='hub_hubuser_jobber__0bf752_idx',
            old_name='hub_hubuser_jobber__idx',
        ),
        migrations.RenameIndex(
            model_name='hubvisit',
            new_name='hub_hubvisi_client__9492e9_idx',
            old_name='hub_hubvisi_client__idx',
        ),
        migrations.RenameIndex(
            model_name='hubvisit',
            new_name='hub_hubvisi_jobber__86f91a_idx',
            old_name='hub_hubvisi_jobber__idx',
        ),
        migrations.RenameIndex(
            model_name='lockinbonus',
            new_name='hub_lockinb_status_94bcc2_idx',
            old_name='hub_lockinb_status_idx',
        ),
        migrations.RenameIndex(
            model_name='lockinbonus',
            new_name='hub_lockinb_technic_b1573e_idx',
            old_name='hub_lockinb_tech_st_idx',
        ),
        migrations.RenameIndex(
            model_name='pendinglockin',
            new_name='hub_pending_client__8e60d1_idx',
            old_name='hub_pending_client__idx',
        ),
        migrations.RenameIndex(
            model_name='pendinglockin',
            new_name='hub_pending_status_e6e337_idx',
            old_name='hub_pending_status_idx',
        ),
        migrations.AddField(
            model_name='hubapikey',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_api_keys_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='hubapikey',
            index=models.Index(fields=['is_active', 'prefix'], name='hub_hubapik_is_acti_46a02d_idx'),
        ),
    ]
