# Generated by Django 5.2.17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0007_lock_in_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="HubTipConfirmLog",
            fields=[
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="tip_confirm_log",
                        serialize=False,
                        to="hub.hubformsubmission",
                    ),
                ),
                ("ran_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-ran_at"],
            },
        ),
    ]
