# Generated by Django 5.2.11 on 2026-08-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0008_hubapikey"),
        ("hub", "0008_hubtipconfirmlog"),
    ]

    operations = []
