# Generated by Django 5.2.11 on 2026-09-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0010_hubuser_display_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="GhlInternalAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("location_id", models.CharField(max_length=100, unique=True)),
                (
                    "firebase_api_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("firebase_refresh_token", models.TextField(blank=True, default="")),
                ("firebase_access_token", models.TextField(blank=True, default="")),
                ("firebase_id_token", models.TextField(blank=True, default="")),
                ("firebase_custom_token", models.TextField(blank=True, default="")),
                (
                    "leadconnector_bearer_token",
                    models.TextField(blank=True, default=""),
                ),
                ("access_token", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_reviews_synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "GHL internal auth",
            },
        ),
        migrations.CreateModel(
            name="GhlGoogleReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ghl_id", models.CharField(max_length=64, unique=True)),
                (
                    "reviewer_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("star_rating", models.PositiveSmallIntegerField(default=0)),
                ("source", models.IntegerField(default=247)),
                ("deleted", models.BooleanField(default=False)),
                ("date_added", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date_added"],
                "indexes": [
                    models.Index(
                        fields=["source", "deleted", "star_rating", "date_added"],
                        name="hub_ghlgoog_source_d573a1_idx",
                    )
                ],
            },
        ),
    ]
