# Generated by Django 5.2.11 on 2026-09-21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0011_ghl_google_reviews"),
    ]

    operations = [
        migrations.CreateModel(
            name="HubNotificationEmail",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("label", models.CharField(blank=True, default="", max_length=128)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="HubNotificationEmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_key", models.CharField(max_length=191)),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="hubnotificationemaillog",
            constraint=models.UniqueConstraint(
                fields=("event_key", "email"),
                name="hub_notify_email_log_event_email",
            ),
        ),
    ]
