# Generated by Django 5.x on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0012_hubnotificationemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="hubnotificationemail",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="HubNotifyPrefs",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("both", "Email and SMS"),
                        ],
                        default="both",
                        max_length=16,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Hub notify prefs",
            },
        ),
        migrations.CreateModel(
            name="HubNotificationSmsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_key", models.CharField(max_length=191)),
                ("recipient_key", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="hubnotificationsmslog",
            constraint=models.UniqueConstraint(
                fields=("event_key", "recipient_key"),
                name="hub_notify_sms_log_event_recipient",
            ),
        ),
    ]
