/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as FormsSlugRouteImport } from './routes/forms.$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminResourcesRouteImport } from './routes/admin.resources'
import { Route as AdminPayrollsRouteImport } from './routes/admin.payrolls'
import { Route as AdminFormsRouteImport } from './routes/admin.forms'
import { Route as AdminDataRouteImport } from './routes/admin.data'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminFormsIndexRouteImport } from './routes/admin.forms.index'
import { Route as AdminFormsFormIdSubmissionsRouteImport } from './routes/admin.forms.$formId.submissions'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const FormsSlugRoute = FormsSlugRouteImport.update({
  id: '/forms/$slug',
  path: '/forms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayrollsRoute = AdminPayrollsRouteImport.update({
  id: '/payrolls',
  path: '/payrolls',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsIndexRoute = AdminFormsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminFormsRoute,
} as any)
const AdminFormsFormIdSubmissionsRoute =
  AdminFormsFormIdSubmissionsRouteImport.update({
    id: '/$formId/submissions',
    path: '/$formId/submissions',
    getParentRoute: () => AdminFormsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/forms': typeof AdminFormsRouteWithChildren
  '/admin/payrolls': typeof AdminPayrollsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/forms/$slug': typeof FormsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/forms/': typeof AdminFormsIndexRoute
  '/admin/forms/$formId/submissions': typeof AdminFormsFormIdSubmissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/payrolls': typeof AdminPayrollsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/forms/$slug': typeof FormsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/forms': typeof AdminFormsIndexRoute
  '/admin/forms/$formId/submissions': typeof AdminFormsFormIdSubmissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/forms': typeof AdminFormsRouteWithChildren
  '/admin/payrolls': typeof AdminPayrollsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/forms/$slug': typeof FormsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/forms/': typeof AdminFormsIndexRoute
  '/admin/forms/$formId/submissions': typeof AdminFormsFormIdSubmissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/calendar'
    | '/admin/dashboard'
    | '/admin/data'
    | '/admin/forms'
    | '/admin/payrolls'
    | '/admin/resources'
    | '/admin/settings'
    | '/forms/$slug'
    | '/admin/'
    | '/admin/forms/'
    | '/admin/forms/$formId/submissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/calendar'
    | '/admin/dashboard'
    | '/admin/data'
    | '/admin/payrolls'
    | '/admin/resources'
    | '/admin/settings'
    | '/forms/$slug'
    | '/admin'
    | '/admin/forms'
    | '/admin/forms/$formId/submissions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/calendar'
    | '/admin/dashboard'
    | '/admin/data'
    | '/admin/forms'
    | '/admin/payrolls'
    | '/admin/resources'
    | '/admin/settings'
    | '/forms/$slug'
    | '/admin/'
    | '/admin/forms/'
    | '/admin/forms/$formId/submissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FormsSlugRoute: typeof FormsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/forms/$slug': {
      id: '/forms/$slug'
      path: '/forms/$slug'
      fullPath: '/forms/$slug'
      preLoaderRoute: typeof FormsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payrolls': {
      id: '/admin/payrolls'
      path: '/payrolls'
      fullPath: '/admin/payrolls'
      preLoaderRoute: typeof AdminPayrollsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data': {
      id: '/admin/data'
      path: '/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms/': {
      id: '/admin/forms/'
      path: '/'
      fullPath: '/admin/forms/'
      preLoaderRoute: typeof AdminFormsIndexRouteImport
      parentRoute: typeof AdminFormsRoute
    }
    '/admin/forms/$formId/submissions': {
      id: '/admin/forms/$formId/submissions'
      path: '/$formId/submissions'
      fullPath: '/admin/forms/$formId/submissions'
      preLoaderRoute: typeof AdminFormsFormIdSubmissionsRouteImport
      parentRoute: typeof AdminFormsRoute
    }
  }
}

interface AdminFormsRouteChildren {
  AdminFormsIndexRoute: typeof AdminFormsIndexRoute
  AdminFormsFormIdSubmissionsRoute: typeof AdminFormsFormIdSubmissionsRoute
}

const AdminFormsRouteChildren: AdminFormsRouteChildren = {
  AdminFormsIndexRoute: AdminFormsIndexRoute,
  AdminFormsFormIdSubmissionsRoute: AdminFormsFormIdSubmissionsRoute,
}

const AdminFormsRouteWithChildren = AdminFormsRoute._addFileChildren(
  AdminFormsRouteChildren,
)

interface AdminRouteChildren {
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDataRoute: typeof AdminDataRoute
  AdminFormsRoute: typeof AdminFormsRouteWithChildren
  AdminPayrollsRoute: typeof AdminPayrollsRoute
  AdminResourcesRoute: typeof AdminResourcesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalendarRoute: AdminCalendarRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDataRoute: AdminDataRoute,
  AdminFormsRoute: AdminFormsRouteWithChildren,
  AdminPayrollsRoute: AdminPayrollsRoute,
  AdminResourcesRoute: AdminResourcesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FormsSlugRoute: FormsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
